ocha_entraid.settings:
  type: config_object
  label: 'OCHA Entra ID settings'
  mapping:
    uimc_api:
      type: mapping
      label: 'UIMC API settings.'
      mapping:
        token_url:
          type: string
          label: 'The API URL to get an access token.'
        registration_url:
          type: string
          label: 'The API URL to register an account.'
        user_details_url:
          type: string
          label: 'The API URL to get details about an account.'
        group_management_url:
          type: string
          label: 'The API URL to add/remove an account from a group.'
        username:
          type: string
          label: 'The API user name.'
        password:
          type: string
          label: 'The API user password.'
        consumer_key:
          type: string
          label: 'The API consumer key.'
        consumer_secret:
          type: string
          label: 'The API consumer secret.'
        send_email:
          type: boolean
          label: 'Whether or not have an email sent after registration.'
        verify_ssl:
          type: boolean
          label: 'Whether to verify SSL or not when querying the API. Useful for local/dev tests.'
        request_timeout:
          type: integer
          label: 'Timeout for requests to the UIMC API.'
        default_group:
          type;: string
          label: 'The default group to which add accounts allowed to log in the site.'
        encryption_key:
          type;: string
          label: '256 bits encryption key used to encrypt the access tokens.'
    messages:
      type: mapping
      label: 'User messages'
      mapping:
        invalid_email:
          type: label
          label: 'Message for invalid email address.'
        login_explanation:
          type: text
          label: 'Explanation text for the login process.'
        login_account_blocked:
          type: label
          label: 'Message when account is blocked.'
        login_account_not_found:
          type: label
          label: 'Message when account is not found during login.'
        login_account_verification_error:
          type: label
          label: 'Message for account verification error during login.'
        login_redirection error:
          type: label
          label: 'Message for an error during the redirection to Microsoft sign in page.'
        registration_explanation:
          type: text
          label: 'Explanation text for the registration process.'
        registration_invalid_first_name:
          type: label
          label: 'Message for invalid first name during registration.'
        registration_invalid_last_name:
          type: label
          label: 'Message for invalid last name during registration.'
        registration_invalid_email:
          type: label
          label: 'Message for invalid email during registration.'
        registration_success:
          type: label
          label: 'Message for successful registration.'
        registration_success_with_email:
          type: label
          label: 'Message for successful registration with email notification enabled.'
        registration_failure:
          type: label
          label: 'Message for failed registration.'
